---
title: "Making the least of your Data Scientist"
author: "Edwin Thoen"
output: html_document
base-url: https://EdwinTh.github.io
date: "2018-05"
tags: [data science, business]
---

You have hired one, or maybe even several, of these highly sought after, well educated, super bright data scientists. Sure, they don't come cheaply, but your innovation manager at Humongous Inc assured you that they "turn data into gold!" and that "we need these people in order to renew our company for the future". Of course you don't really want them to change the way your company is doing business. Nobody likes change, especially not at Humongous Inc. With these ... pro tips, you are assured the data scientist will achieve as little as possible, leaving things as they always were.

## Put them in a busy environment

These are times of cutting costs, so we don't want to have empty desks at Humomgous. Research indicated that we only need to have 0.74 desks available for each employee, since not everybody is in all the time. Desk availability is first come first serve. Desks are cramped together in these large workspaces, to fit in as many people into an office. These are optimal conditions for complete unproductivity. Data science requires a lot of contemplating and rumination, there is no better way to disturb this by a busy and crowded place. Having to find a new desk each day is also a great way of making those precious boys and girls feel nice and uncomfortable.

## Don't bother about data quality



## Do not use open source software

Humongous Inc has a huge and expensive contract with Dinosaur Software and its sales manager assured you that its newest Data Science product is top notch. It has convenient a graphical interface, so the analist doesn't have to bother about writing code. It comes with 31 out-of-the-box algorithms and it has numerous plotting options. Why would your data scientist want to work with anything else? Open source, that sounds like home-written software that can never be used in business life. No, if he knows his trade, he certainly will be better-off using Dinosaur's flashy GUI.

## Keep them separate from business

## Let them work on corporate infrastructure

## Organize a ton of meetings

At Humongous Inc we sure like our meetings, what is work without meetings. Way over half our time is spent in meetings. Weekly meetings to catch up, biweekly meetings to discuss the progress of some project, and also, very modern, a daily standup that usually lasts for over an hour. Of course our data scientist is going to be part of these meetings as well! How else is she going to keep up with company progress. 


