---
title: "Some More Thoughts on Impostering"
author: "Edwin Thoen"
base-url: https://EdwinTh.github.io
categories: blog
layout: post
date: "2020-01-07 16:30:00"
output: html_document
tags: [imposter syndrome, data science, intellectual humility]
---

Two years ago, I wrote about [meta-learning to fight imposter feelings](https://edwinth.github.io/meta-learning/). In this blog I made a distinction between impostering because you don't feel you are up to the job, and because you feel you ought to know something which you don't. The meta-learning blog focuses on how you define yourself as a data scientist and what, as a consequence, you decide to learn (and more importantly what not). Staying sane while doing data science is something that always has my interest. Imposter feelings are a major foe to the joy this work can bring. I came across/to two more insights on the topic that I found worthwhile sharing. The first is *intellectual humility*, which I learned about in the book *Superforecasters, the art & science of prediction* by Philip Tetlock. The second is seeing impostering as a learning alarm, thereby turning it to something positive. 

## Intellectual Humility

*Superforecasters* is not about data science, but about forecasting single events, as typically done by intelligence agencies. I thought it was a very interesting read overall, but what I want to highlight here is its treatment of the concept of *intellectual humility*. 

Just like the forecasters, data scientists are faced with complex problems to which there is no perfect solution. Whether doing machine learning, statistical modelling or an exploratory data analysis, we try to paint an overall picture from incomplete information. We have to look carefully at nonlinear relationships, interaction effects and weak correlations. All very difficult for the human mind to conceive. Often the task ahead is daunting and when we are not careful it can quickly inflict feelings of being incapable. Tetlock discusses that the best forecasters are very aware of their limitations and the possibility that their judgement might be off. But at the same time these forecasters do not doubt that they are the person for the job:

*The humility required for good judgement is not self-doubt - the sense that you are untalented, unintelligent, or unworthy. It is intellectual humility. It is the recognition that reality is profoundly complex, that seeing things clearly is a constant struggle, when it can be done at all, and that human judgement must therefore be riddled with mistakes. This is true for fools and geniuses alike. So it's quite possible to think highly of yourself and be intellectual humble. In fact, this combination can be wonderfully fruitful. Intellectual humility compels the careful reflection necessary for good judgement; confidence in one's abilities inspires determined action.* Superforecaster p. 228-229

I usually refrain from a *You got this!* approach to fight imposter feelings, because I honestly don't know if you do. I don't know it for a reader I have never spoken to, and frankly I often don't know it for myself. Therefore, I typically focus on the *ought to know* part. However, what I realized when reading Tetlock, was that the fact that you are puzzled by the problem you are working on, is by no means an indication you are a phoney. Acknowledging that data science is freaking, freaking hard is not a sign of weakness, it is a sign of realism. Don't look at data science problems as something you are ought to solve on a whim. They are mysteries and only by hard work and perseverance you can chip away some of that mystery and you might even get to insights that are useful.

## Learning Alarm

Now turning to my favorite *ought to know* part of impostering. The feeling of shame, when someone else knows stuff that you don't. You, the data scientist, does not know this simple thing and therefore you deserve to be fired, to be stripped of all your diplomas and work as a store clerk for the rest of your life. Turn that feeling of shame into a learning alarm. Be excited that you discovered something new, something you can add to your knowledge stack. 

Focusing on the shame part of *ought-to-know* will turn you attention inwards. Chances are that you are so busy giving yourself a hard time that you don't use the opportunity to learn. It is completely useless to ruminate on if you should have known this already. Fact is that you don't. Instead turn your attention outwards. If it is another person's ability that induced the feeling, don't shy away or, even worse, pretend like you know (yes, I have done this myself). Pick their brain! Otherwise, Google, read blogs, practice, whatever is needed to master the new material.

## Thanks for Reading

I realize these two topics are a little less applicable than the earlier blog and are a little more philosophical in nature. Still, I hope you find them as practical. They serve as default responses for situations data scientists can be confronted with; being puzzled by the problem they are trying to solve and not knowing something they think they should.
